window.SEED_EXEMPLO = [
    {
      type: 'sell',
      title: 'TBIO Calibre • 12t • Cristalina-GO',
      quantity_ton: 12,
      min_lot_ton: 1,
      price_per_ton: 1550,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'TBIO Calibre',
      harvest: '2025',
      specs: { ph: 81, protein: 14.0, don: 0, moisture: 12.3 },
      location: { city: 'Cristalina', uf: 'GO' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Melhorador',
        w: 300,
        falling_number: 300,
        impurezas: 1,
        endereco: 'Cristalina/GO',
        img: '.assets/img/1 (1).jpg'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'TBIO Duque • 18t • Perdizes-MG',
      quantity_ton: 18,
      min_lot_ton: 1,
      price_per_ton: 1650,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'TBIO Duque',
      harvest: '2025',
      specs: { ph: 79, protein: 13.5, don: 500, moisture: 12.5 },
      location: { city: 'Perdizes', uf: 'MG' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Branqueador',
        w: 250,
        falling_number: 280,
        impurezas: 1,
        endereco: 'Perdizes/MG',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'BRS 264 • 4t • Araguari-MG',
      quantity_ton: 4,
      min_lot_ton: 1,
      price_per_ton: 1500,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'BRS 264',
      harvest: '2025',
      specs: { ph: 79, protein: 13.8, don: 1000, moisture: 12.0 },
      location: { city: 'Araguari', uf: 'MG' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Pão',
        w: 220,
        falling_number: 260,
        impurezas: 2,
        endereco: 'Araguari/MG',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'Biotrigo Valente • 8t • Unaí-MG',
      quantity_ton: 8,
      min_lot_ton: 1,
      price_per_ton: 1600,
      pricing_mode: 'per_ton',
      incoterm: 'CIF',
      cultivar: 'Biotrigo Valente',
      harvest: '2025',
      specs: { ph: 83, protein: 14.3, don: 200, moisture: 11.5 },
      location: { city: 'Unaí', uf: 'MG' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Branqueador',
        w: 330,
        falling_number: 280,
        impurezas: 1,
        endereco: 'Unaí/MG',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'TBIO Duque • 29t • Rio Verde-GO',
      quantity_ton: 29,
      min_lot_ton: 1,
      price_per_ton: 1450,
      pricing_mode: 'per_ton',
      incoterm: 'CIF',
      cultivar: 'TBIO Duque',
      harvest: '2024',
      specs: { ph: 80, protein: 13.1, don: 0, moisture: 12.0 },
      location: { city: 'Rio Verde', uf: 'GO' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Pão',
        w: 320,
        falling_number: 280,
        impurezas: 0.5,
        endereco: 'Rio Verde/GO',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'TBIO Sinuelo • 10t • Jataí-GO',
      quantity_ton: 10,
      min_lot_ton: 1,
      price_per_ton: 1580,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'TBIO Sinuelo',
      harvest: '2025',
      specs: { ph: 80, protein: 13.9, don: 200, moisture: 12.1 },
      location: { city: 'Jataí', uf: 'GO' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Melhorador',
        w: 310,
        falling_number: 290,
        impurezas: 1,
        endereco: 'Jataí/GO',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'BRS Parrudo • 15t • Uberaba-MG',
      quantity_ton: 15,
      min_lot_ton: 2,
      price_per_ton: 1620,
      pricing_mode: 'per_ton',
      incoterm: 'CIF',
      cultivar: 'BRS Parrudo',
      harvest: '2025',
      specs: { ph: 82, protein: 14.2, don: 0, moisture: 12.4 },
      location: { city: 'Uberaba', uf: 'MG' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Pão',
        w: 280,
        falling_number: 310,
        impurezas: 1,
        endereco: 'Uberaba/MG',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'TBIO Toruk • 20t • Chapadão do Sul-MS',
      quantity_ton: 20,
      min_lot_ton: 1,
      price_per_ton: 1520,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'TBIO Toruk',
      harvest: '2025',
      specs: { ph: 81, protein: 13.0, don: 300, moisture: 12.6 },
      location: { city: 'Chapadão do Sul', uf: 'MS' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Branqueador',
        w: 250,
        falling_number: 270,
        impurezas: 2,
        endereco: 'Chapadão do Sul/MS',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'BRS 404 • 7t • Londrina-PR',
      quantity_ton: 7,
      min_lot_ton: 1,
      price_per_ton: 1700,
      pricing_mode: 'per_ton',
      incoterm: 'CIF',
      cultivar: 'BRS 404',
      harvest: '2024',
      specs: { ph: 84, protein: 14.5, don: 0, moisture: 11.8 },
      location: { city: 'Londrina', uf: 'PR' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Melhorador',
        w: 340,
        falling_number: 320,
        impurezas: 0.5,
        endereco: 'Londrina/PR',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell',
      title: 'TBIO Sonic • 25t • Passo Fundo-RS',
      quantity_ton: 25,
      min_lot_ton: 5,
      price_per_ton: 1480,
      pricing_mode: 'per_ton',
      incoterm: 'FOB',
      cultivar: 'TBIO Sonic',
      harvest: '2025',
      specs: { ph: 80, protein: 13.6, don: 600, moisture: 12.2 },
      location: { city: 'Passo Fundo', uf: 'RS' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: {
        wheat_type: 'Pão',
        w: 260,
        falling_number: 290,
        impurezas: 1,
        endereco: 'Passo Fundo/RS',
        img: 'img/Rectangle 160.png'
      },
      _source: 'fixed'
    },
    {
      type: 'sell', title: 'BRS 254 • 30t • Dourados-MS',
      quantity_ton: 30, min_lot_ton: 5, price_per_ton: 1500, pricing_mode: 'per_ton', incoterm: 'CIF',
      cultivar: 'BRS 254', harvest: '2025',
      specs: { ph: 82, protein: 13.2, don: 0, moisture: 12.0 },
      location: { city: 'Dourados', uf: 'MS' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: { wheat_type: 'Branqueador', w: 280, falling_number: 310, impurezas: 1, endereco: 'Dourados/MS', img: 'img/Rectangle 160.png' },
      _source: 'fixed'
    },
    {
      type: 'sell', title: 'TBIO Duque • 12t • Cascavel-PR',
      quantity_ton: 12, min_lot_ton: 1, price_per_ton: 1600, pricing_mode: 'per_ton', incoterm: 'FOB',
      cultivar: 'TBIO Duque', harvest: '2024',
      specs: { ph: 81, protein: 13.4, don: 200, moisture: 12.1 },
      location: { city: 'Cascavel', uf: 'PR' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: { wheat_type: 'Melhorador', w: 300, falling_number: 280, impurezas: 1, endereco: 'Cascavel/PR', img: 'img/Rectangle 160.png' },
      _source: 'fixed'
    },
    {
      type: 'sell', title: 'Biotrigo Audaz • 16t • Goiânia-GO',
      quantity_ton: 16, min_lot_ton: 2, price_per_ton: 1550, pricing_mode: 'per_ton', incoterm: 'CIF',
      cultivar: 'Biotrigo Audaz', harvest: '2025',
      specs: { ph: 83, protein: 14.1, don: 0, moisture: 11.9 },
      location: { city: 'Goiânia', uf: 'GO' },
      owner: { id: 'system', name: 'TRI-GO' },
      meta: { wheat_type: 'Pão', w: 290, falling_number: 300, impurezas: 1, endereco: 'Goiânia/GO', img: 'img/Rectangle 160.png' },
      _source: 'fixed'
    }

  ]

